apiVersion: v1
kind: Pod
metadata:
  name: configmap-test
spec:
  containers:
    - name: test-container
      image:  docker.io/busybox:latest
      command: [ "/bin/sh", "-c", "env" ]
      env: 
        - name: REDHAT_URL
          valueFrom:
            configMapKeyRef:
              name: config1
              key: url.properties
      envFrom:
        - configMapRef:
            name: config2 
  restartPolicy: Never
