apiVersion: v1
kind: Pod
metadata:
  name: configmap-test
spec:
  containers:
    - name: test-container
      image:  docker.io/busybox:latest
      command: [ "/bin/sh", "-c", "env" ]
      env: 
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config 
              key: special.how 
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config 
              key: special.type 
              optional: true 
          envFrom:
          - configMapRef:
              name: env-config 
  restartPolicy: Never
